[ALG-000] Solve: BOJ 문제 2914번 풀이
Glenn-syj/just-do-algorithms pull request #4
Opened 2024-01-24 04:51 UTC by undeadtimo

이건 뭘까... 머지가 머지... 심장이 커밋커밋...
필수 문제 SWEA의 레더와 달팽이 문제 해결 코드와
공통 문제 난이도 (중) 에서 크로아티아 알파벳 문제 해결 코드 및 과정을 정리한 md파일을 추가하였다.

2024-01-24 04:56 UTC, Glenn-syj commented
File name format과 폴더 구조를 지켜주세요.

2024-01-24 05:00 UTC, Glenn-syj requested changes
File Format과 폴더 구조를 지켜주세요.

2024-01-24 06:00 UTC, ucream11 requested changes

2024-01-24 06:00 UTC, ucream11 commented on undeadtimo/week000/SWEA/D4/1210. Ladder1/Week000_1210_SWEA_송창용.java
SWEA <-> 1210 위치 컨벤션 어쩌고

2024-01-24 06:00 UTC, ucream11 commented on undeadtimo/week000/백준/Bronze/1157. 단어 공부/Week000_1157_백준_송창용.java
백준 <-> 1157 위치 컨벤션 어쩌고

2024-01-24 08:39 UTC, minukHwang commented on undeadtimo/week000/백준/Silver/2941. 크로아티아 알파벳/백준 문제 2941번 풀이.md
> +***if( i < len - 3 && word.substring(i, i + 3).equals( cro[j] ))*** 로 조건을 설정해버렸고, 마지막 위치에 존재하는 크로아티아를 탐색하지 못하여 실패를 반복했었다.
아주 디테일한걸

2024-01-24 08:40 UTC, minukHwang approved these changes
😮‍💨

2024-01-24 10:08 UTC, celestedayoung approved these changes

2024-01-24 10:08 UTC, celestedayoung commented on undeadtimo/백준/Silver/2941. 크로아티아 알파벳/Week0_BOJ_2941_송창용.java
> +				if (i < len - 2 && word.substring(i, i + 3).equals(cro[j])) {
저도 substring 썼어요~

2024-01-24 10:13 UTC, qkrrjsxor approved these changes

2024-01-24 23:21 UTC, ucream11 requested changes

2024-01-24 23:21 UTC, ucream11 commented on undeadtimo/week000/백준/Bronze/1157. 단어 공부/Week000_1157_백준_송창용.java
파일명 1157 <-> 백준 위치 초동역학 전환 부탁드릴게요

2024-01-25 02:43 UTC, Glenn-syj approved these changes

2024-01-25 02:45 UTC, ucream-sh approved these changes
Approve땅땅땅

2024-01-25 02:46 UTC, merged

2024-01-25 02:59 UTC, undeadtimo commented on undeadtimo/week000/백준/Silver/2941. 크로아티아 알파벳/Week000_백준_2941_송창용.java
> +		String[] cro = { "dz=", "c=", "c-", "d-", "lj", "nj", "s=", "z=" };
뒤에 있는 dz=까지 중복 적용되어 논리적 오류가 일어납니다!
따라서 dz= 만을 위한 조건문을 만들고, 이후에 나머지 요소들을 이용한 조건문을 통해 로직을 전개해야 합니다!