[ALG-003] Solve: 백준 2805 풀이 // Try: 백준 11279, 1914, 24511 / SWEA 1231 시도
Glenn-syj/just-do-algorithms pull request #52
Opened 2024-02-14 08:32 UTC by ucream-sh

[ALG-003] Solve: 백준 2805 풀이
[ALG-03] Try: 백준 11279, 1914, 24511 / SWEA 1231 시도

2805문제는 pdf도 함께 푸쉬했습니다.
공통문제들을 죄다 Try만 남겼는데 늦게라도 풀 수 있다면 풀어보겠습니다.

2024-02-14 08:56 UTC, Glenn-syj commented
다음에는 커밋 컨벤션을 조금 더 신경 써주세요!

2024-02-14 08:57 UTC, Glenn-syj approved these changes
문제에 접근하고 고민하고 깨져보는 것도 굉장히 중요한 경험입니다!

2024-02-14 08:59 UTC, ucream-sh commented
아 커밋 뭐야 세상에 상태가 좀 안좋았던거같습니다.. 아 커밋 수정하고싶은데 아쉽네요

2024-02-14 13:18 UTC, Glenn-syj requested changes
Main이 아닌 자신의 이름에 해당하는 branch로 merge해주세요

2024-02-15 00:09 UTC, Glenn-syj approved these changes

2024-02-15 00:09 UTC, ucream-sh commented
중요한 걸 체크 못했네요! 수정하겠습니다 감사합니다.

pr close하고 다시 올려야하나 했는데, edit버튼 누르고 pr올릴 브랜치를 수정할 수 있어서 제 브랜치로 변경했습니다~ 이번주도 고생많았습니다

2024-02-15 00:09 UTC, merged